/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
    export interface GlobalComponents {
        AddFoodForm: (typeof import("./src/components/AddFoodForm/index.vue"))["default"];
        CountdownBar: (typeof import("./src/components/CountdownBar/index.vue"))["default"];
        CountdownTimer: (typeof import("./src/components/CountdownTimer/index.vue"))["default"];
        Dialog: (typeof import("./src/components/Dialog/index.vue"))["default"];
        ElButton: (typeof import("element-plus/es"))["ElButton"];
        ElDialog: (typeof import("element-plus/es"))["ElDialog"];
        ElDrawer: (typeof import("element-plus/es"))["ElDrawer"];
        ElEmpty: (typeof import("element-plus/es"))["ElEmpty"];
        ElForm: (typeof import("element-plus/es"))["ElForm"];
        ElFormItem: (typeof import("element-plus/es"))["ElFormItem"];
        ElInput: (typeof import("element-plus/es"))["ElInput"];
        FoodsList: (typeof import("./src/components/FoodsList/index.vue"))["default"];
        FoodsListCard: (typeof import("./src/components/FoodsListCard/index.vue"))["default"];
        RouterLink: (typeof import("vue-router"))["RouterLink"];
        RouterView: (typeof import("vue-router"))["RouterView"];
        RunningLightButton: (typeof import("./src/components/RunningLightButton/index.vue"))["default"];
        SvgIcon: (typeof import("./src/components/SvgIcon/index.vue"))["default"];
        SwitchTheme: (typeof import("./src/components/SwitchTheme/SwitchTheme.vue"))["default"];
    }
}
