version: "3.8"

services:
    nginx:
        image: nginx
        container_name: hot-pot-countdown
        ports:
            - "80:18080"
        volumes:
            - "./nginx.conf:/etc/nginx/nginx.conf"
            - "./dist:/etc/nginx/html"
#         depends_on:
#             - xxxx
#         networks:
#             - mynetwork
# networks:
#     mynetwork:
#         name: ikun
