version: "3.8"

services:
    nginx:
        image: nginx
        container_name: vue3-template
        ports:
            - "80:18080"
        volumes:
            - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./nginx/dist:/etc/nginx/html"
#         depends_on:
#             - xxxx
#         networks:
#             - mynetwork
# networks:
#     mynetwork:
#         name: ikun
